# Ninja or Unix Make can be used.
##include(${CMAKE_CURRENT_LIST_DIR}/cmake/renesas-rh850-ccrh-toolchain-ex1.cmake)
##include(${CMAKE_CURRENT_LIST_DIR}/cmake/renesas-rh850-ccrh-toolchain-ex2.cmake)
##include(${CMAKE_CURRENT_LIST_DIR}/cmake/renesas-rh850-ccrh-toolchain-ex3.cmake)
##include(${CMAKE_CURRENT_LIST_DIR}/cmake/renesas-rh850-ccrh-toolchain-ex4.cmake)
##include(${CMAKE_CURRENT_LIST_DIR}/cmake/renesas-rh850-ccrh-toolchain-ex5.cmake)
##include(${CMAKE_CURRENT_LIST_DIR}/cmake/renesas-rh850-ccrh-toolchain-ex6.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/cmake/renesas-rh850-ccrh-toolchain-ex11.cmake)
#include(${CMAKE_CURRENT_LIST_DIR}/cmake/renesas-rh850-ccrh-toolchain-ex12.cmake)
#include(${CMAKE_CURRENT_LIST_DIR}/cmake/renesas-rh850-ccrh-toolchain-ex13.cmake)
#include(${CMAKE_CURRENT_LIST_DIR}/cmake/renesas-rh850-ccrh-toolchain-ex14.cmake)
#include(${CMAKE_CURRENT_LIST_DIR}/cmake/renesas-rh850-ccrh-toolchain-ex15.cmake)
#include(${CMAKE_CURRENT_LIST_DIR}/cmake/renesas-rh850-ccrh-toolchain-ex16.cmake)
